/**
 * Locations Finder block — centered heading + structural search form.
 * Rows: 0 eyebrow | 1 heading | 2 body | 3 input placeholder | 4 submit CTA (label + action href).
 * The form markup is generated by the decorator; only its text is authored.
 * @param {Element} block The locations-finder block element
 */
export default function decorate(block) {
  const rows = [...block.children];

  const eyebrow = rows[0]?.textContent.trim() || '';
  const heading = rows[1]?.textContent.trim() || '';
  const body = rows[2]?.textContent.trim() || '';
  const placeholder = rows[3]?.textContent.trim() || '';
  const submitLink = rows[4]?.querySelector('a');
  const submitLabel = submitLink?.textContent.trim() || 'Search';
  const action = submitLink?.getAttribute('href') || '/locations';

  const container = document.createElement('div');
  container.className = 'container';

  if (eyebrow) {
    const eb = document.createElement('span');
    eb.className = 'eyebrow';
    eb.textContent = eyebrow;
    container.append(eb);
  }
  if (heading) {
    const h2 = document.createElement('h2');
    h2.textContent = heading;
    container.append(h2);
  }
  if (body) {
    const p = document.createElement('p');
    p.textContent = body;
    container.append(p);
  }

  const form = document.createElement('form');
  form.className = 'search-row';
  form.setAttribute('action', action);
  form.setAttribute('method', 'get');
  form.setAttribute('role', 'search');
  form.setAttribute('aria-label', 'Find a Frescopa location');

  const input = document.createElement('input');
  input.type = 'text';
  input.name = 'q';
  input.placeholder = placeholder;
  input.setAttribute('aria-label', 'Search by ZIP code, city, or state');

  const submit = document.createElement('button');
  submit.type = 'submit';
  submit.className = 'btn btn-primary-on-bay';
  submit.textContent = submitLabel;

  form.append(input, submit);
  container.append(form);

  block.textContent = '';
  block.append(container);
}
